dist: trusty
sudo: required
cache: pip
language: python
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "pypy3.5-5.8.0"
    - os: osx
      osx_image: xcode9.4
      language: generic
  allow_failures:
    - os: osx
    - python: "pypy3.5-5.8.0"
  fast_finish: true
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_PYTHON_VERSION" != "3.6" ]]; then travis_terminate 0; fi; # Deploy on 3.6
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m venv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
  - pip install -U pip
  - pip install codecov
  - pip install coverage
  - pip install -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then pip install -e azure-storage-nspkg; fi;  # Would work on Python 3, but will not be installed by PyPI. Trying to be close to real life.
  - pip install -e azure-storage-common
  - pip install -e azure-storage-blob
  - pip install -e azure-storage-file
  - pip install -e azure-storage-queue
script:
  - coverage run -m unittest discover
after_success:
  - coverage report
  - codecov
notifications:
  webhooks:
    urls:
      - https://outlook.office.com/webhook/a4aad5a1-3f32-42c8-8a5e-903446565be3@72f988bf-86f1-41af-91ab-2d7cd011db47/TravisCI/a018a63e5e994165a2a56b0dd4c62120/3d491bab-ac74-4d43-aeeb-f4b674cb5466
    on_success: never # default: always
    on_failure: always # default: always
    on_start: never   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
