dist: trusty
sudo: required
cache: pip
language: python
matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.3"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "nightly"
    - os: linux
      python: "pypy3.5-5.8.0"
    - os: osx
      osx_image: xcode7.3
      language: generic
  allow_failures:
    - os: osx
    - python: "3.3"
    - python: "pypy3.5-5.8.0"
    - python: "nightly"
  fast_finish: true
# Perform the manual steps on osx to install python3 and activate venv
before_install:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_PYTHON_VERSION" != "3.6" ]]; then travis_terminate 0; fi; # Deploy on 3.6
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m venv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install wheel
  - python build_packages.py all
  - pip install dist/*.whl
script: 
  - python -m unittest discover
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
